# Enable the H2 Console

# The path where you can access it in the browser
spring.h2.console.path=/h2-console

# Persistence configuration
#spring.datasource.url=jdbc:h2:mem:cashback_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password


# Replace us-east-1 and the XXXXX with your actual Region and User Pool ID
aws.cognito.issuer-uri=arn:aws:cognito-idp:us-east-2:608659035826:userpool/us-east-2_OfWs7erUH

# AWS Credentials (If not using IAM roles or Default Credentials Chain)
# Tell Spring Cloud AWS which region you are in
spring.cloud.aws.region.static=us-east-2
# Optional: Tell it to stop looking for EC2 metadata (speeds up startup)
spring.cloud.aws.credentials.instance-profile=false
AWS_REGION=us-east-2

# S3 Bucket for Receipt Storage
aws.s3.bucket=cashback-king-receipts


# File Upload Limits (Increase for high-res receipt images)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Server Port
server.port=8080

# Logging for Analytics Debugging
logging.level.com.bhatn.cashbackking=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# 1. The exact Issuer (ensure NO spaces at the end of the line)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_OfWs7erUH

# 2. Add the explicit JWK Set URI as a backup
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_OfWs7erUH/.well-known/jwks.json


# 3. Increase logging to see the EXACT mismatch in the console
logging.level.org.springframework.security=DEBUG

#RazorPay config--
razorpay.key.id=rzp_test_STA2qKQxfMKOz5
razorpay.key.secret=q0KKfy5H7sTFemq8sj3v2UD5
razorpay.account.number=2323230057482840


# Supabase Transaction Pooler Configuration
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.obtcvvfhnjpsivygxjua
spring.datasource.password=Magical845123845
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.main.lazy-initialization=true

# Disable H2 to prevent driver confusion
spring.h2.console.enabled=false


logging.level.org.springframework.security.oauth2=DEBUG

spring.jpa.defer-datasource-initialization=true
spring.datasource.hikari.initialization-fail-timeout=-1
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.idle-timeout=60000
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false